name: 'Run Tests'

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-project:
          - 'Examples.Tests/Halite.Serialization.Examples.Tests.csproj'
          - 'JsonNet.Tests/Halite.Serialization.JsonNet.Tests.csproj'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: 'Restore ${{ matrix.test-project }}'
        run: dotnet restore ${{ matrix.test-project }}

      - name: 'Build ${{ matrix.test-project }}'
        run: dotnet build ${{ matrix.test-project }} --configuration Release --no-restore

      - name: 'Test ${{ matrix.test-project }}'
        run: dotnet test ${{ matrix.test-project }} --no-restore